### PR TITLE
Added some further information about Samathy Barratt

### PR DESCRIPTION
**Pull request by Samathy**
Included talk topics and website.

### CODE REVIEW

**Comment by Charlotteis** [comment]
Hey!

Mind getting rid of the space that you introduced on line 558?
Also, each person only gets one link (for the time being), could you choose twitter or your website please? :)

**Comment by Charlotteis** [comment]
Bump!

**Comment by Samathy** [comment]
Finally got around to doing this!

**Comment by Charlotteis** [comment]
Cheers!

**Pull request merged**
